version: '3.8'

services:
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database-blog
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  api:
    build:
      context: ./api-blog
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      NOTION_API_KEY: ${NOTION_API_KEY}
      GCP_PROJECT_ID: ${GCP_PROJECT_ID}
      GCS_BUCKET_NAME: ${GCS_BUCKET_NAME}
      GOOGLE_APPLICATION_CREDENTIALS: /app/gcp/project-key.json # Path inside the container
      API_KEY: ${API_KEY}
      IS_DOCKER: "true"
      GIN_MODE: "release"
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/app/gcp/project-key.json # Mount host path to container path

  front:
    build:
      context: ./front-blog
      dockerfile: Dockerfile
    depends_on:
        - api
    ports:
      - "3000:3000"
    environment:
      API_URI: http://localhost:8080
      FRONT_URI: http://localhost:3000
      API_KEY: ${API_KEY}

volumes:
  postgres_data:


