services:
  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database-blog
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  api:
    build:
      context: ./api-blog
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      API_KEY: ${API_KEY}
      GIN_MODE: "release"
  front:
    build:
      context: ./front-blog
      dockerfile: Dockerfile
      args:
        API_URI: ${API_URI}
        API_KEY: ${API_KEY}
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
  postgres_data:


