// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Posts struct {
	ID           int32            `json:"id"`
	Title        string           `json:"title"`
	Content      string           `json:"content"`
	Slug         string           `json:"slug"`
	Description  string           `json:"description"`
	ThumbnailUrl string           `json:"thumbnail_url"`
	UserID       int32            `json:"user_id"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type Users struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	Email     string           `json:"email"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
