// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: postcategories.sql

package database

import (
	"context"
)

const attachCategory = `-- name: AttachCategory :one
INSERT INTO postcategories (post_id, category_id)
VALUES ($1,$2)
RETURNING id, post_id, category_id
`

type AttachCategoryParams struct {
	PostID     int32 `json:"post_id"`
	CategoryID int32 `json:"category_id"`
}

func (q *Queries) AttachCategory(ctx context.Context, arg AttachCategoryParams) (Postcategories, error) {
	row := q.db.QueryRow(ctx, attachCategory, arg.PostID, arg.CategoryID)
	var i Postcategories
	err := row.Scan(&i.ID, &i.PostID, &i.CategoryID)
	return i, err
}

const detachCategory = `-- name: DetachCategory :exec
delete from postcategories
    WHERE post_id = $1 and category_id = $2
`

type DetachCategoryParams struct {
	PostID     int32 `json:"post_id"`
	CategoryID int32 `json:"category_id"`
}

func (q *Queries) DetachCategory(ctx context.Context, arg DetachCategoryParams) error {
	_, err := q.db.Exec(ctx, detachCategory, arg.PostID, arg.CategoryID)
	return err
}
